# Get curso by ID
# Example:
# $id "1"
# $capitulo "Capitulo 1"
query ($id: ID!, $capitulo: String!) {
  curso(id: $id) {
    data {
      id
      attributes {
        name
        Capitulos(filters: { name: { eq: $capitulo } }) {
          name
          Contenido {
            id
            text
            image {
              data {
                attributes {
                  alternativeText
                  caption
                  name
                  formats
                }
              }
            }
          }
        }
      }
    }
  }
}
